site_name: emotionalonbroadway
site_url: https://emotionalonbroadway.github.io/
theme:
  name: material
  palette:
    scheme: default
nav: 
  - Home: "index.md"
  - Haves: "haves.md"
  - Wants: "wants.md"
plugins:
  - table-reader:
      data_path: "docs/tables/"
      allow_missing_files: True